version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${{secrets.POSTGRES_USERNAME}}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
  build: .
  container_name: fastapi-app
  ports:
    - "8000:8000"
  environment:
    DATABASE_URL: ${{secrets.POSTGRES_URL}}}
  depends_on:
    - db
  volumes:
    - .:/app
  command:
    [
      "/app/.venv/bin/uvicorn",
      "main:app",
      "--host",
      "0.0.0.0",
      "--port",
      "8000",
      "--reload",
    ]

volumes:
  postgres_data:
