name: Docker CI/CD

on:
  push:
    branches: [CICD]

env:
  REGISTRY: ${{ secrets.REGISTRY_URL }}
  IMAGE_NAME: Blockhouse-backend

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            docker.io/kunalkoshti/blockhouse:${{ github.sha }}
            docker.io/kunalkoshti/blockhouse:latest

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io # Extracts registry domain
          username: ${{ secrets.REGISTRY_USERNAME }} # 'AWS' for ECR
          password: ${{ secrets.REGISTRY_PASSWORD }} # Docker Hub token or ECR secret key
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/docker-app
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
            chmod 600 .env
            docker pull docker.io/kunalkoshti/blockhouse:latest
            docker stop fastapi-container || true
            docker rm fastapi-container || true
            docker-compose run -d \
              --name fastapi-container \
              -p 8000:8000 \
              --env-file .env\
              --restart unless-stopped \
              docker.io/kunalkoshti/blockhouse:latest
