name: Docker CI/CD

on:
  push:
    branches: [CICD]

env:
  REGISTRY: ${{ secrets.REGISTRY_URL }}
  IMAGE_NAME: Blockhouse-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/var/docker-app
            git config --global user.email "kunal.koshti15@gmail.com" user.name "kunal" user.password "kunal@150"
            git remote set-url origin https://github.com/kunalkoshti/Blockhouse-backend.git
            git fetch origin CICD
            git checkout CICD
            git pull origin CICD
            docker-compose up --build
